# Generated by Django 4.2.7 on 2023-12-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=255)),
                ('time_create', models.TimeField(auto_now_add=True)),
                ('time_update', models.TimeField(auto_now=True)),
            ],
        ),
    ]
